/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 33b9483935ea2d68bc008fd8173cd3df)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		OA1_BRIDGE_JOBS: KVNamespace;
		OA1_BRIDGE_PRESENCE: KVNamespace;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
