/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 33b9483935ea2d68bc008fd8173cd3df)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker");
  }
  interface Env {
    MACHINEN_BRIDGE_JOBS: KVNamespace;
    MACHINEN_BRIDGE_PRESENCE: KVNamespace;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
